enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
        gradlePluginPortal()
    }
}

rootProject.name = "IvyWallet"
include(":app")
include(":ci-actions:base")
include(":ci-actions:issue-assign")
include(":ci-actions:issue-create-comment")
include(":screen:accounts")
include(":screen:attributions")
include(":screen:balance")
include(":screen:budgets")
include(":screen:categories")
include(":screen:contributors")
include(":screen:edit-transaction")
include(":screen:exchange-rates")
include(":screen:features")
include(":screen:home")
include(":screen:import-data")
include(":screen:loans")
include(":screen:main")
include(":screen:onboarding")
include(":screen:piechart")
include(":screen:planned-payments")
include(":screen:releases")
include(":screen:reports")
include(":screen:search")
include(":screen:settings")
include(":screen:transactions")
include(":shared:base")
include(":shared:common-ui")
include(":shared:data")
include(":shared:data-testing")
include(":shared:design-system")
include(":shared:domain")
include(":shared:navigation")
include(":shared:resources")
include(":shared:testing")
include(":temp:legacy-code")
include(":temp:old-design")
include(":widget:shared-base")
include(":widget:add-transaction")
include(":widget:balance")
