name: Import CSV Request
description: Request an import CSV from specific app to be supported.
title: "[IMPORT] {APP_NAME} ({PACKAGE_NAME})"
labels: ["user request"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm the following
      options:
        - label: I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems
          required: true
  - type: input
    id: url-to-app
    attributes:
      label: Google PlayStore URL to the app from which you want to import
      placeholder: https://play.google.com/store/apps/details?id=com.cool.app
    validations:
      required: false
  - type: textarea
    id: csv-sample
    attributes:
      label: Attach Samples CSV from the app
      description: Attach an exported CSV file from the app to this issue.
    validations:
      required: false
  - type: dropdown
    id: requirements
    attributes:
      label: CSV file requirements
      multiple: true
      options:
        - includes Income type transaction
        - includes Expense type transaction
        - includes Transfer type transaction (optional)
        - includes title, description, all attributes available in the app (optional)
    validations:
      required: false
  - type: dropdown
    id: cost
    attributes:
      label: Is CSV export from the app free?
      options:
        - "Yes"
        - "No"
        - It depends
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Developer/Contributor Notes
      description: Just a few notes for developers. Ignore the content and don't change it, please.
      value: |
        - Checkout this **[Sample Commit](https://github.com/Ivy-Apps/ivy-wallet/commit/323ed68343a0904ee33f226480716a30368fd646)** to see how import CSV works in Ivy Wallet
        - Make sure that the imported dates of the transactions are correct"
    validations:
      required: true
