direction: down

feature: ":feature modules" {
    ui: "Compose UI" {
        "Usually a Screen"
        "Destination in the Navigation graph"
    }
    state: "UI State" {
        "Data class only of Compose primitives"
    }
    event: "Event" {
        "ADT with all possible user interactions"
    }
    vm: "ViewModel" {
        "Produces UI State"
        "Handles Event"
    }

    actions: "Actions (impure)" {
        "Feature-level actions"
    }

    ui -> state: "Latest state"
    ui -> event: "User interactions"
    state -> vm: "Produced by the ViewModel"
    event -> vm: "Sent to the ViewModel"
    vm -> actions: "Feauture-level logic"
}
feature.ui -> core-ui.uiComponents: "@Composables"
feature.actions -> core-ui.barrier: "Read-only Flows (RX) + Calculations (pure)"
feature.actions -> core-domain.barrier: "Write Actions (impure) + Reading Snapshots (impure)"

core-ui {
    barrier: Abstraction Barrier {
        fill: "#f0ff3a"
        "Read Actions (impure)" {
            "Flow (RX)"
        }
        "Calculations (pure)" {
            "E.g. format: Value -> Boolean -> ValueUi"
        }
    }

    uiComponents: UI Components {
        fill: "#f0ff3a"
        "Compose UI" {
            "UI Components"
            "Modals"
        }
    }

    
    uiMap: "Map Domain to UI data" {
        "Data -> DataUi (e.g. Transaction -> TransactionUi)"
    }

    barrier -> uiMap
    uiComponents -> uiMap
}
core-ui.uiMap -> core-domain.barrier: "Read-only Flows (RX)"


core-domain {
    barrier: Abstraction Barrier {
        fill: "#f0ff3a"
        "Write Actions (impure)" {
            suspend
        }
        read: "Read Actions (impure)" {
            "Flow (RX)"
            "suspend (snapshot)"
        }
    }

    calculations: "Caculations" {
        "Pure processing layer"
    }

    data: "Domain Data" {
        "ADTs describing the domain"
    }

    barrier -> calculations -> data
}
core-domain.data -> core-persistence.barrier: "Write/Read from persistence as Domain"
core-domain -> core-exchange-provider

core-persistence {
    barrier: Abstraction Barrier {
        fill: "#f0ff3a"
        read: "Read Actions (impure)" {
            "Flow (RX)"
            "suspend (snapshot)"
        }
        write: "Write Actions (impure)" {
            "suspend"
        }
    }

    validation: "Validation layer (pure)" {
        "Ensures data being written is correct"
        "Ensures data being read is correct"
    }

    db: "Relational Database" {
        sql: "SQL tables" {
            shape: cylinder
        }
    }

    datastore: "DataStore" {
        kvs: "Key-Value Storage" {
            shape: cylinder
        }
    }

    barrier.read -> validation: "Validate reads"
    barrier.write -> validation: "Validate writes"
    validation -> db
    validation -> datastore
}

core-data-model {
    fill: purple
    font-color: white
    data: "Domain data" {
        Transaction
    }
    optimized: "Optimzed" {
        "Select only the needed parts of the domain data"
        TrnHistory
        TrnCalc
    }
}
core-domain -> core-data-model
core-persistence -> core-data-model

core-exchange-provider {
    "Fetches remote exchange rates for a base-currency"
}

# Other services
sms-parser {
    "Parses transactions from SMS"
}
sms-parser -> core-domain.barrier

notifications-parser {
    "Parses transactions from Notifications"
}
notifications-parser -> core-domain.barrier


sync {
    fetch: "Fetches Backup JSON from Google Drive"
    merge: "Merges the data with the local DB"
    upload: "Uploads data to Google Drive"
}
sync -> google-drive
sync -> backup

backup {
    "Export backup JSON"
    "Import backup JSON"
    "Import old backup JSON"
}
backup -> core-domain.barrier: "Read data snapshot / Write to persistence"


google-drive {
    "GoogleDriveService: get & upload data to drive"
}