# Accounts
accounts {
    shape: sql_table
    id: uuid {constraint: primary_key}
    name: "string"
    icon_id: "string"
    color_int: "int"
    asset_code: "string"
    order_num: "double"
    archived: "boolean"
    include_in_balance: "boolean"
    type: "int: Asset.Cash(1) | Asset.Bank(2) | Asset.Loan(3)\
        | Asset.Investment(4) | Asset.Other(5)\
        | Liability.CreditCard(-1) | Liability.Loan(-2) | Liability.Other(-3)"
}

credit_card_info {
    shape: sql_table
    account_id: uuid {constraint: primary_key}
    statement_days: "int: 1-31"
    due_days: "int: 1-31""
}
credit_card_info -> accounts: "\"account_id\" FK"

loan_info {
    shape: sql_table
    account_id: uuid {constraint: primary_key}
}
loan_info -> accounts: "\"account_id\" FK"
# Accounts


# Sync
sync {
    shape: sql_table
    item_id: "uuid" {constraint: foreign_key}
    state: "int: Syncing | Deleted | Synced"
    last_updated: "long: epoch seconds"
}
sync -> transactions: "\"item_id\" FK"
sync -> due_transactions: "\"item_id\" FK"
sync -> accounts: "\"item_id\" FK"
sync -> categories: "\"item_id\" FK"
sync -> recurring_rules: "\"item_id\" FK"
# Sync


# Categories
categories {
    shape: sql_table
    id: uuid {constraint: primary_key}
    name: string
    icon_id: "string"
    color_int: "int"
    order_num: "double"
    parent_category_id: "uuid (optional)" {constraint: foreign_key}
}
categories -> categories: "\"parent_category_id\" FK"
# Categories


# Tags
trn_tag_join {
    shape: sql_table
    transaction_id: uuid {constraint: primary_key}
    tag_id: uuid {constraint: primary_key}
}
trn_tag_join -> transactions: "\"transction_id\" FK"
trn_tag_join -> tags: "\"tag_id\" FK"
tags {
    shape: sql_table
    id: uuid {constraint: primary_key}
    name: string
    color_int: "int"
    order_num: "double"
}
# Tags


# Attachments
trn_attachement_join {
    shape: sql_table
    attachment_id: uuid {constraint: primary_key}
    tag_id: uuid {constraint: primary_key}
}
trn_attachement_join -> transactions: "\"transction_id\" FK"
trn_attachement_join -> attachments: "\"attachment_id\" FK"
attachments {
    shape: sql_table
    id: uuid {constraint: primary_key}
    transaction_id: uuid {constraint: foreign_key}
    uri: "string"
    name: "string"
}
# Attachments


# Recurring
recurring_tag_join {
    shape: sql_table
    recurring_rule_id: uuid {constraint: primary_key}
    tag_id: uuid {constraint: primary_key}
}
recurring_tag_join -> recurring_rules: "\"recurring_rule_id\" FK"
recurring_tag_join -> tags: "\"tag_id\" FK"

recurring_attachment_join {
    shape: sql_table
    recurring_rule_id: uuid {constraint: primary_key}
    attachment_id: uuid {constraint: primary_key}
}
recurring_attachment_join -> recurring_rules: "\"recurring_rule_id\" FK"
recurring_attachment_join -> attachments: "\"attachment_id\" FK"

recurring_rules {
    shape: sql_table
    id: uuid {constraint: primary_key}
    start_time: "long: epoch seconds"
    interval_seconds: "long"
    end_time: "long: epoch seconds (optional)"
    auto_execute: boolean
    entries_json: "string: entries JSON"
    category_id: "uuid (optional)" {constraint: foreign_key}
    title: "string (optional)"   
    description: "string (optional)"   
}
recurring_rules -> categories: "\"category_id\" FK"
# Recurring


# Ledger & transactions
ledger {
    shape: sql_table
    entry_id: "uuid" {constraint: primary_key}
    from_account: "uuid (optional)" {constraint: foreign_key}
    from_amount: "positive double (optional)"
    from_asset_code: "string (optional)"
    to_account: "uuid (optional)" {constraint: foreign_key}
    to_amount: "positive double (optional)"
    to_asset_code: "string (optional)"
    timestamp: "long: epoch seconds"
    special_purpose: "int: None(0) | Fee(1)"
    transaction_id: "uuid" {constraint: foreign_key}
}
ledger -> accounts: "\"from_account\" FK"
ledger -> accounts: "\"to_account\" FK"
ledger -> transactions: "\"transaction_id\" FK"

transactions {
    shape: sql_table
    id: uuid {constraint: primary_key}
    timestamp: "long: epoch seconds"
    title: "string (optional)"
    description: "string (optional)"
    category_id: "uuid (optional)" {constraint: foreign_key}
    recurring_rule_id: "uuid (optional)" {constraint: foreign_key}
    hidden: "boolean"
}
transactions -> categories: "\"category_id\" FK"
transactions -> recurring_rules: "\"recurring_rule_id\" FK"
# Ledger & transactions


# [DUE] Ledger & transactions
due_ledger {
    shape: sql_table
    entry_id: "uuid" {constraint: primary_key}
    from_account: "uuid (optional)" {constraint: foreign_key}
    from_amount: "positive double (optional)"
    from_asset_code: "string (optional)"
    to_account: "uuid (optional)" {constraint: foreign_key}
    to_amount: "positive double (optional)"
    to_asset_code: "string (optional)"
    timestamp: "long: epoch seconds"
    special_purpose: "int: None(0) | Fee(1)"
    transaction_id: "uuid" {constraint: foreign_key}
}
due_ledger -> accounts: "\"from_account\" FK"
due_ledger -> accounts: "\"to_account\" FK"
due_ledger -> due_transactions: "\"transaction_id\" FK"

due_transactions {
    shape: sql_table
    id: uuid {constraint: primary_key}
    timestamp: "long: epoch seconds"
    title: "string (optional)"
    description: "string (optional)"
    category_id: "uuid (optional)" {constraint: foreign_key}
    recurring_rule_id: "uuid (optional)" {constraint: foreign_key}
}
due_transactions -> categories: "\"category_id\" FK"
due_transactions -> recurring_rules: "\"recurring_rule_id\" FK"
# [DUE] Ledger & transactions


# Account cache
account_cache {
    shape: sql_table
    account_id: uuid {constraint: primary_key}
    incomes_json: "string: RawStats as JSON"
    expenses_json: "string: RawStats as JSON"
    incomes_count: "int"
    expenses_count: "int"
    timestamp: "long: epoch seconds"
}
account_cache -> accounts: "\"account_id\" FK"
# Account cache