sync {
    shape: sql_table
    item_id: "uuid" {constraint: foreign_key}
    state: "int: Syncing | Deleted | Synced"
    last_updated: "long: epoch seconds"
}
sync -> transactions: "\"item_id\" FK"
sync -> accounts: "\"item_id\" FK"
sync -> categories: "\"item_id\" FK"

accounts {
    shape: sql_table
    id: uuid {constraint: primary_key}
    name: "string"
    icon_id: "string"
    color_int: "int"
    asset_code: "string"
    order_num: "double"
    archived: "boolean"
    include_in_balance: "boolean"
    type: "int: Asset.Cash(1) | Asset.Bank(2) | Asset.Loan(3)\
        | Asset.Investment(4) | Asset.Other(5)\
        | Liability.CreditCard(-1) | Liability.Loan(-2) | Liability.Other(-3)"
}

ledger {
    shape: sql_table
    entry_id: "uuid" {constraint: primary_key}
    from_account: "uuid (optional)" {constraint: foreign_key}
    from_amount: "positive double (optional)"
    from_asset_code: "string (optional)"
    to_account: "uuid (optional)" {constraint: foreign_key}
    to_amount: "positive double (optional)"
    to_asset_code: "string (optional)"
    timestamp: "long: epoch seconds"
    transaction_id: "uuid" {constraint: foreign_key}
}
ledger -> accounts: "\"from_account\" FK"
ledger -> accounts: "\"to_account\" FK"
ledger -> transactions: "\"transaction_id\" FK"

transactions {
    shape: sql_table
    id: uuid {constraint: primary_key}
    title: "string (optional)"
    description: "string (optional)"
    category_id: "uuid (optional)" {constraint: foreign_key}
    hidden: "boolean"
}
transactions -> categories: "\"category_id\" FK"

categories {
    shape: sql_table
    id: uuid {constraint: primary_key}
    name: string
    icon_id: "string"
    color_int: "int"
    order_num: "double"
    parent_category_id: "uuid (optional)" {constraint: foreign_key}
}
categories -> categories: "\"parent_category_id\" FK"
