ivy-res: ":ivy-resources" {
  "Shared resources"
  "strings and drawables"
}
ivy-base: ":ivy-base" {
  "Code shared everywhere"
}
ivy-data: ":ivy-data" {
  "CRUD: Room DB, Datastore, HTTP"
}
ivy-domain: ":ivy-domain" {
  "Core API: domain rules & business logic"
}
ivy-domain-ui: ":ivy-domain-ui" {
  "UI components that has domain logic"
}
ivy-nav: ":ivy-navigation" {
  "Definition (w/o implementation) for all screens in Ivy Wallet"
}
ivy-design: ":ivy-design" {
  "Ivy's design system"
}
screens: ":screen-something" {
  ":screen-home"
  ":screen-settings"
  ":screen-abc"
  ":screen-xyz"
}
app: ":app" {
  "Ivy Wallet app's monolith shipped to the PlayStore"
  "Wires the implementation of all Ivy Wallet screens"
}

ivy-data -> ivy-base
ivy-domain -> ivy-data
ivy-domain -> ivy-base

ivy-design -> ivy-res
ivy-nav -> ivy-domain
ivy-nav -> ivy-design

ivy-domain-ui -> ivy-nav

screens -> ivy-domain-ui
screens -> ivy-nav
screens -> ivy-res

app -> screens
