ivy-res: ":ivy-resources" {
  "Shared common resources"
  "Contains all Ivy Wallet resources"
}
ivy-core: ":ivy-core" {
  "Core API: domain logic + CRUD"
}
ivy-core-ui: ":ivy-core-ui" {
  "Reusable Ivy Wallet high-level UI components"
}
ivy-nav: ":ivy-navigation" {
  "Startup params for all Screen destinations in Ivy Wallet"
}
ivy-design: ":ivy-design" {
  "Ivy's design system (low-level)"
}
screens: ":screen-something" {
  ":screen-home"
  ":screen-settings"
  ":screen-abc"
  ":screen-xyz"
}
app: ":app" {
  "Ivy Wallet app's monolith shipped to the PlayStore"
  "Wires the implementation of all Ivy Wallet screens"
}

ivy-design -> ivy-res
ivy-nav -> ivy-core
ivy-nav -> ivy-design

ivy-core-ui -> ivy-nav

screens -> ivy-core-ui
screens -> ivy-nav
screens -> ivy-res

app -> screens
