name: CI Actions tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Enable Gradle Wrapper caching (optimization)
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test the CI actions "base"
        run: ./gradlew :ci-actions:base:test

      - name: Test the CI "issue-assign" action
        run: ./gradlew :ci-actions:issue-assign:test

      - name: Test the CI "issue-create-comment" action
        run: ./gradlew :ci-actions:issue-create-comment:test

      - name: Test the CI "compose_stability" action
        run: ./gradlew :ci-actions:compose-stability:test

      - name: Test the CI "pr-description-check" action
        run: ./gradlew :ci-actions:pr-description-check:test