name: Screenshots tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sceenshot_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Enable Gradle Wrapper caching (optimization)
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Compose preview screenshot tests
        run: ./gradlew :shared:ui:testing:validateDebugScreenshotTest

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: my-artifact
          path: shared/ui/testing/build/reports