name: Screenshots tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sceenshot_test:
    runs-on: macos-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Run Compose preview screenshot tests
        run: ./gradlew validateDebugScreenshotTest

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: my-artifact
          path: screen/onboarding/build/reports