name: "Danger JS"

on:
  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Danger
        uses: danger/danger-js@9.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
