name: Paparazzi screenshots tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sceenshot_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Run Paparazzi screenshot tests
        run: ./gradlew verifyPaparazziDebug
